---
  test_name: Adding a comment to an article that dosen't exist

  stages:
    - name: Add a comment to an article that dosen't exist
      request:
        url: http://localhost:5000/comment
        auth:
            - parag
            - bhingre

        json:
          comment: 'Hey!!!!! I am from San Jose'
          article_id: 20
        method: POST
        headers:
          content-type: application/json
      response:
        status_code: 409

---
 test_name: Post an anonymous comment on an article

 stages:
   - name: Post an anonymous comment on an article
     request:
       url: http://localhost:5000/comment
       json:
         comment: 'Hey!!!!! this article is awesome'
         article_id: 1
       method: POST
       headers:
         content-type: application/json
     response:
       status_code: 201
---
test_name: Post an authenticated comment on an article

stages:
  - name: Post an authenticated comment on an article
    request:
      url: http://localhost:5000/comment
      auth:
        - parag
        - bhingre

      json:
        comment: "Hey!!!!! this article is from valid user"
        article_id: 1
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 201

---
test_name: Comment order

stages:
  - name: return comments in order
    request:
      url: "http://localhost:5000/comment?article_id=1"
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 200
